app = "cel-rpc-gateway"
primary_region = "sin"

[build]
  dockerfile = "../Dockerfile.go-service"
  [build.args]
    SERVICE = "rpc-gateway"

[env]
  RPC_GATEWAY_HTTP_PORT = "8089"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 8089
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
